- name: Deploy filebeat fully
  hosts: all
  become: true
  gather_facts: false
  vars_files:
    - ../vault.yml

  tasks:

    - name: Ensure GPG is installed for apt_key
      apt:
        name: gnupg
        state: present

    - name: Add Elastic GPG key
      ansible.builtin.apt_key:
        url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        state: present

    - name: Add Elastic APT repository
      ansible.builtin.apt_repository:
        repo: "deb https://artifacts.elastic.co/packages/8.x/apt stable main"
        state: present
        filename: elastic

    - name: Update APT cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Filebeat
      ansible.builtin.apt:
        name: filebeat
        state: present

    - name: Deploy Filebeat configuration
      ansible.builtin.copy:
        src: ../config_files/filebeat.yml
        dest: /etc/filebeat/filebeat.yml
        owner: root
        group: root
        mode: '0644'

    - name: Ensure certs directory exists
      ansible.builtin.file:
        path: /etc/filebeat/certs
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Copy Elastic CA certificate
      ansible.builtin.copy:
        src: ../certs/http_ca.crt
        dest: /etc/filebeat/certs/http_ca.crt
        owner: root
        group: root
        mode: '0644'

    - name: Enable Filebeat service
      ansible.builtin.systemd:
        name: filebeat
        enabled: true

    - name: Validate Filebeat config (dry run)
      ansible.builtin.command: filebeat test config -c /etc/filebeat/filebeat.yml
      register: filebeat_config_test
      changed_when: false
      failed_when: filebeat_config_test.rc != 0

    - name: Print config test result
      ansible.builtin.debug:
        var: filebeat_config_test.stdout

#  handlers:
